import React from 'react'

export default function weekview() {
    return (
          <div className="w-auto flex-1 grid grid-cols-8 grid-rows-16">
            <div></div><div className="border border-gray-200 flex flex-col items-center">Lunes</div><div className="border border-gray-200 flex flex-col items-center">Martes</div><div className="border border-gray-200 flex flex-col items-center">Miercoles</div><div className="border border-gray-200 flex flex-col items-center">Jueves</div><div className="border border-gray-200 flex flex-col items-center">Viernes</div><div className="border border-gray-200 flex flex-col items-center">Sabado</div><div className="border border-gray-200 flex flex-col items-center">Domingo</div>
            <div className="text-xs pb-3 flex flex-col items-center">7am</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">8am</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">9am</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">10am</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">11am</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">12pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">1pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">2pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">3pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">4pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">5pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">6pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">7pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">8pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
            <div className="text-xs pb-3 flex flex-col items-center">9pm</div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div><div className="border border-gray-200 flex flex-col items-center"></div>
          </div> 
        )
}
  